pipeline {
  agent any

  parameters {
    string(name: 'FEDORA_IP', defaultValue: '172.30.242.229', description: 'IP address of Fedora server')
    string(name: 'SSH_USER', defaultValue: 'sktuser', description: 'SSH user to connect as')
    booleanParam(name: 'REBOOT_SERVER', defaultValue: false, description: 'Check to reboot the Fedora server')
  }

  stages {
    stage('Checkout') {
      steps {
        // Checkout using the Git credential stored in Jenkins (jenkinsgit)
        checkout([$class: 'GitSCM',
          branches: [[name: '*/main']],
          userRemoteConfigs: [[
            url: 'https://github.com/akmayuga/jenkins.git',
            credentialsId: 'jenkinsgit'
          ]]
        ])
      }
    }

    stage('Verify / Ping') {
      steps {
        echo "Params: FEDORA_IP=${params.FEDORA_IP}, SSH_USER=${params.SSH_USER}, REBOOT=${params.REBOOT_SERVER}"
        // Optional: simple ping test to check reachability
        sh "ping -c 2 ${params.FEDORA_IP} || true"
      }
    }

    stage('Reboot Fedora') {
      when {
        expression { return params.REBOOT_SERVER == true }
      }
      steps {
        // Use SSH credentials added in Jenkins (ID of your 'sktuser' private key)
        sshagent (credentials: ['3c3b3d3b-aa8c-4cda-a744-57ee8d56d62e']) {
          // Run remote reboot via ssh. -o StrictHostKeyChecking=no avoids prompt for unknown host keys.
          sh """
            ssh -o StrictHostKeyChecking=no sktuser@${params.FEDORA_IP} sudo reboot
          """
        }
      }
    }
  }

  post {
    success { echo 'Pipeline completed successfully' }
    failure { echo 'Pipeline failed - check console output' }
  }
}
